# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Schedule Me' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Schedule Me
  pod ‘SwiftMoment’
  pod ‘DateTimePicker’
  pod ‘DropDown’
  pod 'CVCalendar', '~> 1.4.1'

  target 'Schedule MeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
